from time import sleep
from random import randint
import emoji
from combat_area import ceu_nuvens,eyes_normal,hp_hero,legs,floor,teto,div,hp_vilain,fire,fist,arrow,arrow_dmg,fire_dmg,fist_dmg,fire_sword,firesword_dmg,special,espaco


print(f'\033[1;90m {espaco}')
print(f'\033[1;37m Então voce nunca pisou por aqui ? Fique tranquilo vou te esninar tudo que precisa!')
print(f'\033[1;90m {espaco}')
sleep (1.5)
print(f'\033[1;37m Começe escolhendo um dos ataques abaixo !')
sleep (1.5)
print(f'                                       {teto}')
print(f'{ceu_nuvens}')
print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10      |')
print(f'{eyes_normal}')
print(f'                                       |  § {special} / 3     -|-                                     -|-      |')
print(f'{legs}')
print(f'{div}')
print(f'                                       |  {arrow} = {arrow_dmg} DMG  /  {fire} = {fire_dmg} DMG /   {fist} = {fist_dmg} DMG     |')
print(f'{floor}')

print(f'\033[1;90m {espaco}')
print(f'\033[1;37m A cada ataque seu § aumenta! ')
sleep(0.5)
print(f' \033[1;37m Quando chegar no maximo voce libera o seu ataque especial !')
print(f'\033[1;90m {espaco}')
sleep(0.5)

for c in range(0, 2) :
    print(f' 1 - {arrow}')
    print(f' 2 - {fire}')
    print(f' 3 - {fist}')
    sel_atk = int(input('-->  '))
    if sel_atk == 1 :
            sleep(1.3)
            print(f'\033[1;90m {espaco}')
            print(f'\033[1;37m Voce atacou com o {arrow}! hp \033[1;92m /-{arrow_dmg}/')
            sleep(2)
            print(f'\033[1;90m {espaco}')
            print('\033[1;37m Veja seu § esta aumentando !')
            hp_vilain -= arrow_dmg
            special += 1
            print(f' \033[1;37m                                         {teto}')
            print(ceu_nuvens)
            print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10        |')
            print(eyes_normal)
            print(f'                                       |  § {special} / 3     -|-                                    -|-       |')
            print(legs)
            print(div)
            print(f'                                       |  {arrow} = {arrow_dmg} DMG  /  {fire} = {fire_dmg} DMG /   {fist} = {fist_dmg} DMG     |')       
            print(floor)
    if sel_atk == 2 :
            sleep(1.3)
            print(f'\033[1;90m {espaco}')
            print(f'\033[1;37m Voce atacou com o {fire}! hp /\033[1;92m -{fire_dmg}/')
            sleep(2)
            print(f'\033[1;90m {espaco}')
            print('\033[1;37m Veja seu § esta aumentando !')
            print(f'\033[1;90m {espaco}')
            hp_vilain -= fire_dmg
            special += 1
            print(f' \033[1;37m                              {teto}')
            print(ceu_nuvens)
            print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10        |')
            print(eyes_normal) 
            print(f'                                       |  § {special} / 3     -|-                                    -|-       |')
            print(legs)
            print(div)
            print(f'                                       |  {arrow} = {arrow_dmg} DMG  /  {fire} = {fire_dmg} DMG /   {fist} = {fist_dmg} DMG     |')        
            print(floor)
    if sel_atk == 3 :
            sleep(1.3)
            print(f'\033[1;37m Voce atacou com o {fist}! hp /\033[1;92m -{fist_dmg}/')
            sleep(2)
            print(f'\033[1;90m {espaco}')
            print('\033[1;37m Veja seu § esta aumentando !')
            print(f'\033[1;90m {espaco}')
            hp_vilain -= fist_dmg
            special += 1
            print(f' \033[1;37m                              {teto}')
            print(ceu_nuvens)
            print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10        |')
            print(eyes_normal)
            print(f'                                       |  § {special} / 3     -|-                                    -|-       |')
            print(legs)
            print(div)
            print(f'                                       |  {arrow} = {arrow_dmg} DMG  /  {fire} = {fire_dmg} DMG /   {fist} = {fist_dmg} DMG     |')        
            print(floor)
sleep (1.2)
print(f'\033[1;90m {espaco}')
print('\033[1;37m Muito bem ! Voce esta pegando o jeito !')

villain = randint(1,3)
if villain == 1 :
    sleep(2)
    print(f'\033[1;90m {espaco}')
    print(f'\033[1;37m  Voce foi atingido pelo {arrow}! hp\033[1;31m  /-{arrow_dmg}/')
    print(f'\033[1;90m {espaco}')
    hp_hero -= arrow_dmg
    print(f' \033[1;37m                              {teto}')
    print(ceu_nuvens)
    print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10       |')
    print(eyes_normal)
    print(f'                                       |  § {special} / 3     -|-                                    -|-       |')
    print(legs)
    print(div)
    print(f'                                       |  {arrow} = {arrow_dmg} DMG  /  {fire} = {fire_dmg} DMG /   {fist} = {fist_dmg} DMG     |')    
    print(floor)
if villain == 2 :
    sleep(1.3)
    print(f'\033[1;90m {espaco}')
    print(f'\033[1;37m  Voce foi atingido pelo {fire}! hp \033[1;31m /-{fire_dmg}/')
    print(f'\033[1;90m {espaco}')
    hp_hero -= fire_dmg
    print(f' \033[1;37m                              {teto}')
    print(ceu_nuvens)
    print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10        |')
    print(eyes_normal)
    print(f'                                       |  § {special} / 3     -|-                                    -|-       |')
    print(legs)
    print(div)
    print(f'                                       |  {arrow} = {arrow_dmg} DMG  /  {fire} = {fire_dmg} DMG /   {fist} = {fist_dmg} DMG     |')   
    print(floor)
if villain == 3 :
    sleep(1.3)
    print(f'\033[1;90m {espaco}')
    print(f'\033[1;37m  Voce foi atingido pelo {fist} ! hp\033[1;31m  /-{fist_dmg}/')
    print(f'\033[1;90m {espaco}')
    hp_hero -= fist_dmg
    print(f' \033[1;37m                              {teto}')
    print(ceu_nuvens)
    print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10        |')
    print(eyes_normal)
    print(f'                                       |  § {special} / 3     -|-                                    -|-       |')
    print(legs)
    print(div)
    print(f'                                       |  {arrow} = {arrow_dmg} DMG  /  {fire} = {fire_dmg} DMG /   {fist} = {fist_dmg} DMG     |')   
    print(floor)

sleep (1.3)
print(f'\033[1;90m {espaco}')
print('\033[1;37m Cuidado não podemos substima-lo !')
sleep (2)
print(f'\033[1;90m {espaco}')
print('\033[1;37m OLhe seu \033[1;33m §pecial \033[1;37m esta pronto ! Utilize-o pra finalizar com ele !')
print(f'\033[1;90m {espaco}')
sleep(1.5)
print(f' \033[1;37                                      {teto}')
print(ceu_nuvens)
print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10        |')
print(eyes_normal)
print(f'                                       |  § {special} / 3     -|-                                     -|-     |')
print(legs)
print(div)
print(f'                                       |                    {fire_sword} = {firesword_dmg} DMG                   |')   
print(floor)


sleep(0.8)
print(f'\033[1;90m {espaco}')
print(f' 1 - {fire_sword}')
sel_atk = int(input('-->  '))
if sel_atk == 1 :
    sleep(2)
    print(f'\033[1;90m {espaco}')
    print(f'\033[1;37m Voce atacou com o {fire_sword}\033[1;92m ! hp /-{firesword_dmg}/')
    hp_vilain = 0
    print(f' \033[1;37m                                      {teto}')
    print(ceu_nuvens)
    print(f'                                       |              {hp_hero}/10                                 {hp_vilain}/10        |')
    print(eyes_normal)
    print(f'                                       |  § {special} / 3     -|-                                   -|-      |')
    print(legs)
    print(div)
    sleep(1.3)
    print(f'                                       |                    V O C E   V E N C E U   ! ! !              |')       
    print(floor)

sleep(2)
print(f'\033[1;90m {espaco}')
print('\033[1;92m T U T O R I A L    C O M P L E T O  !!!')
print(f'\033[1;90m {espaco}')
#python tutorial_chapter.py

